export {default as About} from './about/About'
export {default as Home} from './home/Home'
export {default as Profile} from './profile/Profile'
export {default as NotFound} from './notfound/NotFound'
export {default as Research} from './research/Research'
export {default as Contact} from './contact/Contact'