export { default as Header } from './header/Header'
export { default as Jumbotron } from './jumbotron/Jumbotron'
export { default as Footer } from './footer/Footer'
export { default as Page } from './page/Page'
export { default as SPH } from './sph/SPH'
export {default as SubTitle} from './subtitle/SubTitle'
export {default as Sandbox} from './sandbox/Sandbox'
export {default as Slime} from './slime/Slime'